import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Le Hoang Tuan",
      email: "tuanlhgcs200305@fpt.edu.vn",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Nguyen Hoang Phuong",
      email: "phela101990@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  products: [
    {
      // _id: '1',
      name: "Test1",
      slug: "test1",
      category: "Test",
      img: "/images/test1.jpg",
      price: 100,
      countInStock: 10,
      country: "Testing",
      rating: 4.5,
      numReviews: 10,
      description: "Nice",
    },
    {
      // _id: '2',
      name: "Test2",
      slug: "test2",
      category: "Test",
      img: "/images/test1.jpg",
      price: 100,
      countInStock: 10,
      country: "Testing",
      rating: 5,
      numReviews: 10,
      description: "Nice",
    },
    {
      // _id: '3',
      name: "Test3",
      slug: "test3",
      category: "Test",
      img: "/images/test1.jpg",
      price: 100,
      countInStock: 0,
      country: "Testing",
      rating: 2,
      numReviews: 10,
      description: "Nice",
    },
    {
      // _id: '4',
      name: "Test4",
      slug: "test4",
      category: "Test",
      img: "/images/test1.jpg",
      price: 100,
      countInStock: 10,
      country: "Testing",
      rating: 2.5,
      numReviews: 10,
      description: "Nice",
    },
    {
      // _id: '5',
      name: "Test5",
      slug: "test5",
      category: "Test",
      img: "/images/test1.jpg",
      price: 100,
      countInStock: 0,
      country: "Testing",
      rating: 3.5,
      numReviews: 10,
      description: "Nice",
    },
  ],
};
export default data;
